[package]
authors = ["Michael P. Jung <michael.jung@terreon.de>"]
edition = "2018"
name = "webwire"
version = "0.1.0"

[dependencies]
async-trait = "0.1"
bytes = "0.5"
dashmap = "3.11"
nom = "5.1"
serde_json = "1"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.tokio]
features = ["full"]
version = "0.2"

[dependencies.uuid]
features = ["serde"]
version = "0.8"
