[package]
authors = ["Michael P. Jung <michael.jung@terreon.de>"]
edition = "2018"
name = "webwire"
version = "0.1.0"

[dependencies]
async-trait = "0.1"
bytes = "0.5"
dashmap = "3.11"
futures = "0.3"
hyper = "0.13"
hyper-websocket-lite = "0.3.5"
websocket-codec = "0.3.5"
nom = "5.1"
serde_json = "1"
log = "0.4"

[dependencies.serde]
features = ["derive"]
version = "1"

[dependencies.tokio]
features = ["full"]
version = "0.2"

[dependencies.uuid]
features = ["serde"]
version = "0.8"
